---
- hosts: all
  sudo: true
  vars:
    mysql_root_password: '123'
    sys_packages: [ 'curl', 'vim', 'git', 'mysql-server', 'mysql-common', 'mysql-client', 'python-mysqldb', 'ruby-switch']
    php_packages: [ 'php5-curl', 'php5-cli', 'php5-mysql' ]
    vhosts:
      - server_name: localhost
        file: default
        root: ''
      - server_name: web
        file: web
        root: web

  tasks:
    - include: tasks/init.yml
    - include: tasks/nginxphp.yml
    - include: tasks/mysql.yml
    - include: tasks/ruby.yml
    - include: tasks/nodejs.yml
    - include: tasks/tools.yml
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart php5-fpm
      service: name=php5-fpm state=restarted